server:
  port: 8080

spring:
  application:
    name: MovieRatingApp
  liquibase:
    changeLog: "classpath:/db/database-changelog.xml"

ribbon:
  ServerListRefreshInterval: 1000

management:
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
  secret: "secret_key"

logging:
    level:
      antoniohf.movierating: DEBUG

api:
  version: "v0.1"
swagger:
  enabled: true
  title: "Movie rating API"
  description: "Sample Swagger implementation for the `Movie Rating API` service"
  useDefaultResponseMessages: false
  enableUrlTemplating: false
  deepLinking: true
  defaultModelsExpandDepth: 1
  defaultModelExpandDepth: 1
  displayOperationId: false
  displayRequestDuration: false
  filter: false
  maxDisplayedTags: 0
  showExtensions: false
