server:
  port: 8080

spring:
  application:
    name: MovieRatingApp
  liquibase:
    changeLog: "classpath:/db/database-changelog.xml"

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

jwt:
  secret: "secret_key"

logging:
    level:
      antoniohf.movierating: DEBUG


